###OBTENER LOS USUARIOS
GET http://localhost:3000/users


###OBTENER UN USUARIO POR SU CORREO
GET http://localhost:3000/users/ducho@gmail.com.mx

###OBTENER UN USUARIO Y SU CONTRA
GET http://localhost:3000/users/ducho@gmail.com.mx/12345

###ACTUALIZAMOS UN USUARIO CON UNA NUEVA LISTA
PUT http://localhost:3000/users/updateList/ducho@gmail.com.mx
Content-Type: application/json

{
    "nombre": "pene",
    "apellidos":"vidrio",
    "correo": "ducho@gmail.com.mx",
    "contra": "12345",
    "perrosDadosEnAdopcion": ["luna"],
    "verificado":true
}

###postear un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
    "nombre": "ducho",
    "apellidos":"vidrio",
    "correo": "ducho@gmail.com.mx",
    "contra": "12345",
    "perrosEnAdopcion": [],
    "verificado":false
}

###posteamos a ailin tilin
POST http://localhost:3000/users
Content-Type: application/json

{
    "nombre": "ailin",
    "apellidos":"tilin",
    "correo": "ailintilin@gmail.com.mx",
    "contra": "6789",
    "perrosEnAdopcion": ["Cachi"],
    "verificado":false
}

###posteamos a ximena
POST http://localhost:3000/users
Content-Type: application/json

{
    "nombre": "ximena",
    "apellidos":"isaac",
    "correo": "ximenaisacc@gmail.com.mx",
    "contra": "password",
    "perrosEnAdopcion": [],
    "verificado":false
}

###ACTUALIZAR UN USUARIO EXISTENTE
PUT http://localhost:3000/users/ducho@gmail.com.mx
Content-Type: application/json

{
    "nombre": "ducho",
    "apellidos":"vidrio",
    "correo": "ducho@gmail.com.mx",
    "contra": "12345",
    "perrosEnAdopcion": [],
    "verificado":true
}


/////PERRITOS
###OBTENER LOS PERROS
GET http://localhost:3000/dogs/Luna

//INFO DOGS
###OBTENER X PERRITO
GET http://localhost:3000/infodogs/Beagle

