###OBTENER LOS USUARIOS
GET http://localhost:3000/users

###OBTENER LOS USUARIOS
GET http://localhost:3000/users/prueba@gmail.com

###OBTENER LOS PERROS
GET http://localhost:3000/dogs

###ACTUALIZAR ALGO DE UN USUARIO
PUT http://localhost:3000/users/updateList/prueba@gmail.com
Content-Type: application/json

{
    "perrosDadosEnAdopcion":["SIUU"]
}

###postear un usuario
POST http://localhost:3000/users
Content-Type: application/json

{
    "nombre": "ducho",
    "apellidos":"vidrio",
    "correo": "ducho@gmail.com.mx",
    "contra": "12345",
    "perrosEnAdopcion": []
}

###posteamos a ailin tilin
POST http://localhost:3000/users
Content-Type: application/json

{
    "nombre": "ailin",
    "apellidos":"tilin",
    "correo": "ailintilin@gmail.com.mx",
    "contra": "6789",
    "perrosEnAdopcion": ["Cachi"]
}

###posteamos a ximena
POST http://localhost:3000/users
Content-Type: application/json

{
    "nombre": "ximena",
    "apellidos":"isaac",
    "correo": "ximenaisacc@gmail.com.mx",
    "contra": "password",
    "perrosEnAdopcion": []
}

/////PERRITOS
###OBTENER LOS PERROS
GET http://localhost:3000/dogs

###POSTEAR UN PERRO
POST http://localhost:3000/dogs
Content-Type: application/json

{
    "nombre": "Nombre del Perro",
    "edad": 3,
    "raza": "Raza del Perro",
    "color": "Color del Perro",
    "energia": 5,
    "historialMedico": ["Historial Médico del Perro"],
    "problemasSalud": ["Problemas de Salud del Perro"],
    "medicamentos": "Medicamento1",
    "descripcion": "Descripción del Perro",
    "imagen": "https://example.com/imagen-del-perro.jpg",
    "direccion": "Calle Principal 456",
    "telefono": 5555678,
    "correo": "perro@example.com"
}

//INFO DOGS
###OBTENER X PERRITO
GET http://localhost:3000/infodogs/Beagle

###ACTUALIZAR LA LISTA DE UN USUARIO
PUT http://localhost:3000/users/updateList/@gmail.com
Content-Type: application/json

{
    "nombre": "ducho",
    "apellidos":"ducho",
    "correo": "ducho@gmail.com.mx",
    "contra": "password",
    "perrosDadosEnAdopcion": ["luna"]
}

###POSTEAMOS UN ADMIN
GET http://localhost:3000/admins

###BUSCAMOS UN PERRO EN ESPECIFICO POR ID
DELETE http://localhost:3000/dogs/id/6567ea2eb5e5943cbfe0c993





